---
# tasks file for roles/run-agent
- name: Create jenkins home directory
  ansible.builtin.file:
    state: directory
    path: /home/ubuntu/jenkins_home
    owner: ubuntu
    mode: u=rwx,g=rw,o=rw
    
- name: Get the Public key of the Ec2
  ansible.builtin.shell: |
    cat ~/.ssh/authorized_keys
  register: agent_public_key  

- name: Run jenkins agent container
  community.docker.docker_container:
    name: jenkins_agent
    state: started
    ports:
      - "2200:22"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - source: /home/ubuntu/jenkins_home
        target: /home/jenkins
        type: bind
    env:
      JENKINS_AGENT_SSH_PUBKEY: "{{ agent_public_key.stdout }}"
    restart_policy: always
    detach: true
    image: "anas1243/jenkins-ssh-agent-with-docker"