---
- name: Configure Jenkins Master node
  hosts: jenkins-master
  remote_user: ubuntu
  roles: 
    - roles/install-docker
    - roles/run-master

- name: Configure webserver node
  hosts: flask-webapp
  remote_user: ubuntu
  roles: 
    - roles/install-docker
